[package]
name = "chainlink-tests"
version = "0.0.1"
authors = [ "Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.client]
path = "client"

[dependencies.oracle]
path = "oracle"

[dependencies.aggregator]
path = "aggregator"

[dependencies.exchange]
path = "exchange"

[dependencies.elrond-wasm]
version = "0.14.1"

[dependencies.elrond-wasm-derive]
version = "0.14.1"

[dependencies.elrond-wasm-node]
version = "0.14.1"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.14.1"
