[package]
name = "module-test-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.module-test]
path = ".."

[dependencies.elrond-wasm]
version = "0.30.0"

[dependencies.elrond-wasm-debug]
version = "0.30.0"
