[package]
name = "price-aggregator-proxy"
version = "0.0.0"
authors = [ "",]
edition = "2018"

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-derive]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"
