[package]
name = "price-aggregator-proxy"
version = "0.0.0"
authors = [ "",]
edition = "2018"

[dependencies.elrond-wasm]
version = "0.25.0"

[dependencies.elrond-wasm-derive]
version = "0.25.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.25.0"
