[package]
name = "price-aggregator-proxy"
version = "0.0.0"
authors = [""]
edition = "2018"

[dependencies.multiversx-sc]
version = "0.45.2"

[dependencies.multiversx-sc-derive]
version = "0.34.0"

[dev-dependencies.multiversx-sc-scenario]
version = "0.45.2"
