[Blockchain]
    GasPrice = 1_000_000_000
    ProxyUrl = "https://devnet-gateway.elrond.com"
    ChainID = "D"
    PemPath = "./config/owner.pem"

[GasConfig]
    BatchTxGasLimit = 150_000_000
    FeedTxGasLimit = 30_000_000

[Server]
    Port = ":5000"

[Contract]
    Endpoint = "submit"
    Address = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz"

[PriceFeedBatch]
    Endpoint = "submitBatch"
    Address = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz"
    BatchSize = 100

[GasStation]
    Endpoint = "submitBatch"
    Address = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz"
    TargetAssets = [
        { Ticker = "EGLD", Decimals = 18 },
        { Ticker = "ETH", Decimals = 18 },
        { Ticker = "USDC", Decimals = 6 },
    ]

[Exchange]
    MultiplicationPrecision = 100
    CheckPercentageChange = false
    PercentageThreshold = 2.5
    Pairs = [
        { Base = "EGLD", Quote = "USD" },
        { Base = "ETH", Quote = "USD" },
        { Base = "USDC", Quote = "USD" },
]


