[Blockchain]
    GasPrice = 1_000_000_000
    GasLimit = 100_000_000
    ProxyUrl = "https://testnet-gateway.elrond.com"
    ChainID = "T"
    PemPath = "./config/owner.pem"

[Contract]
    Address = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz"
    Endpoint = "submit"

[Server]
    Port = ":5000"

[Exchange]
    MultiplicationPrecision = 100
    CheckPercentageChange = false
    PercentageThreshold = 2.5
    Pairs = [
        {Base = "EGLD", Quote= "USD", ScAddress = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz", Endpoint = "submit"},
        {Base = "ETH", Quote= "USD", ScAddress = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz", Endpoint = "submit"},
        {Base = "AAVE", Quote= "USD", ScAddress = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz", Endpoint = "submit"},
        {Base = "LINK", Quote= "USD", ScAddress = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz", Endpoint = "submit"},
        {Base = "BTC", Quote= "USD", ScAddress = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz", Endpoint = "submit"},
    ]

[GasConfig]
    GasLimit = 200_000
    TargetAsset = "EGLD"
    TargetAssetDecimals = 18
    TxPremium = 0
    Address = "erd1qqqqqqqqqqqqqpgq2j35zktgvhazpvzrr9m8649gnqz53uydu00sflu9rz"
    Endpoint = "submit"