[package]
name = "exchange-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.exchange]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.2"
default-features = false
