[package]
name = "exchange-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.exchange]
path = ".."

[dependencies.elrond-wasm]
version = "0.31.1"

[dependencies.elrond-wasm-debug]
version = "0.31.1"
