[package]
name = "aggregator"
version = "0.0.1"
authors = [ "Claudiu-Marcel Bruda <claudiu.bruda@elrond.com>",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.22.8"

[dev-dependencies.elrond-wasm-debug]
version = "0.22.8"
